services:
    MrAndMrsSmith\IdempotentConsumerBundle\:
        resource: '../'
        autowire: true
        autoconfigure: true

    _instanceof:
        MrAndMrsSmith\IdempotentConsumerBundle\Resolver\IdempotentKeyResolver:
            public: true
            tags: [ 'idempotent.key_resolver' ]

    MrAndMrsSmith\IdempotentConsumerBundle\Checker\CheckMessageCanBeProcessed:
        class: MrAndMrsSmith\IdempotentConsumerBundle\Checker\CheckMessageCanBeProcessed
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $idempotentKeyResolversRegister: '@MrAndMrsSmith\IdempotentConsumerBundle\Resolver\KeyResolverRegister'
            $processFailedMessageVoter: '@mms.idempotent_consumer.process_failed_message_voter'
    MrAndMrsSmith\IdempotentConsumerBundle\Finalizer\MessageFinalizer:
        class: MrAndMrsSmith\IdempotentConsumerBundle\Finalizer\MessageFinalizer
        autoconfigure: true
        autowire: true
        public: true

    MrAndMrsSmith\IdempotentConsumerBundle\ProcessFailedMessageVoter\DefaultProcessFailedMessageVoter:
        class: MrAndMrsSmith\IdempotentConsumerBundle\ProcessFailedMessageVoter\DefaultProcessFailedMessageVoter
        alias: mms.idempotent_consumer.process_failed_message_voter
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $wantToProcessFailedMessage: false
