name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - develop
      - feature/sonarqube
  pull_request:
    branches:
      - main
      - develop
      - feature/sonarqube

jobs:
  sonarqube-check-idempotent:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarQube Scan
        uses: docker://sonarsource/sonar-scanner-cli:latest
        with:
          args: >
            sonar-scanner
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.login=${{ env.SONAR_TOKEN }}
            -Dsonar.ssl.accept.all=true

  sonarqube-vulnerability-report-idempotent:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: Install curl
        run: sudo apt-get install -y curl
        
      - name: Download SonarQube Vulnerability Report
        run: curl -k -u "${{ env.SONAR_TOKEN }}:" "${{ env.SONAR_HOST_URL }}/api/issues/github_sast_export?projectKey=idempotent-consumer-bundle&branch=${{ github.ref_name }}&pullRequest=${{ github.event.number }}" -o github-sast-sonar-report.json